---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.10-bookworm

inputs:
  - name: dp-frontend-cache-helper
    path: dp-frontend-cache-helper

run:
  path: dp-frontend-cache-helper/ci/scripts/build.sh
